In [2]:
import pandas as pd
import numpy as np

In [32]:
df=pd.read_csv("../data/online_retail_II_full.csv")
df.head()

,invoice,stockcode,quantity,invoice_date,price,customer_id,country,total_price
0,489434,85048,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.4
1,489434,79323P,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
2,489434,79323W,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
3,489434,22041,48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.8
4,489434,21232,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 805549 entries, 0 to 805548
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   invoice       805549 non-null  int64
 1   stockcode     805549 non-null  object
 2   quantity      805549 non-null  int64
 3   invoice_date  805549 non-null  object
 4   price         805549 non-null  float64
 5   customer_id   805549 non-null  int64
 6   country       805549 non-null  object
 7   total_price   805549 non-null  float64
dtypes: float64(2), int64(3), object(3)
memory usage: 49.2+ MB

In [19]:
print(df['customer_id'].value_counts())
print(df[df['customer_id'].isnull()])

customer_id
17841    12890
14911    11245
12748     7228
14606     6566
14096     5111
         ...
15284        1
13864        1
15693        1
16417        1
13290        1
Name: count, Length: 5878, dtype: int64
Empty DataFrame
Columns: [invoice, stockcode, quantity, invoice_date, price, customer_id, country, total_price]
Index: []

In [29]:
df[df['quantity']<0]

Empty DataFrame
Columns: [invoice, stockcode, quantity, invoice_date, price, customer_id, country, total_price]
Index: []

In [15]:
df[df['quantity']<0]['invoice'].value_counts()

Series([], Name: count, dtype: int64)

In [34]:
df.head()

,invoice,stockcode,quantity,invoice_date,price,customer_id,country,total_price
0,489434,85048,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.4
1,489434,79323P,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
2,489434,79323W,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
3,489434,22041,48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.8
4,489434,21232,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0

In [ ]:
# df=df[df['invoice'].astype(str).str.startswith('C')]

In [35]:
df_clean = df[
    (~df['invoice'].astype(str).str.startswith(('C'), na=False)) & 
    (df['customer_id'].notnull()) &
    (df['quantity']>0) &
    (df['price']>0)
]

In [36]:
df_clean.head()

,invoice,stockcode,quantity,invoice_date,price,customer_id,country,total_price
0,489434,85048,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.4
1,489434,79323P,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
2,489434,79323W,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
3,489434,22041,48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.8
4,489434,21232,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0

In [37]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 805549 entries, 0 to 805548
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   invoice       805549 non-null  int64
 1   stockcode     805549 non-null  object
 2   quantity      805549 non-null  int64
 3   invoice_date  805549 non-null  object
 4   price         805549 non-null  float64
 5   customer_id   805549 non-null  int64
 6   country       805549 non-null  object
 7   total_price   805549 non-null  float64
dtypes: float64(2), int64(3), object(3)
memory usage: 49.2+ MB

In [ ]:
df_clean['invoiceDate']=pd.to_datetime(df_clean['invoice_date'])
df_clean['customer ID']=df_clean['customer_id'].astype(int)

In [39]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 805549 entries, 0 to 805548
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   invoice       805549 non-null  int64
 1   stockcode     805549 non-null  object
 2   quantity      805549 non-null  int64
 3   invoice_date  805549 non-null  object
 4   price         805549 non-null  float64
 5   customer_id   805549 non-null  int64
 6   country       805549 non-null  object
 7   total_price   805549 non-null  float64
 8   InvoiceDate   805549 non-null  datetime64[ns]
 9   Customer ID   805549 non-null  int32
dtypes: datetime64[ns](1), float64(2), int32(1), int64(3), object(3)
memory usage: 58.4+ MB

In [ ]:
df_clean.drop(['description'],inplace=True,axis=1)

C:\Users\hj161\AppData\Local\Temp\ipykernel_15524\3895707775.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.drop(['Description'],inplace=True,axis=1)

In [155]:
df_clean.head()

,Invoice,StockCode,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,12,2009-12-01 07:45:00,6.95,13085,United Kingdom
1,489434,79323P,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
2,489434,79323W,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
3,489434,22041,48,2009-12-01 07:45:00,2.10,13085,United Kingdom
4,489434,21232,24,2009-12-01 07:45:00,1.25,13085,United Kingdom

In [ ]:
df_clean['total_price']=df_clean['price']*df_clean['quantity']

C:\Users\hj161\AppData\Local\Temp\ipykernel_15524\1781065077.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['total_price']=df_clean['Price']*df_clean['Quantity']

In [ ]:
# Creates a Period object (Year-Month)
df_clean['Month_Year'] = df_clean['invoice_date'].dt.to_period('M')

KeyError: 'Invoice Date'

In [1]:
df_clean.head()

NameError: name 'df_clean' is not defined

In [160]:
df_clean.columns=df_clean.columns.str.lower()
df_clean.columns=df_clean.columns.str.replace(' ','_')

In [163]:
df_clean.head()

,invoice,stockcode,quantity,invoicedate,price,customer_id,country,total_price,month_year
0,489434,85048,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.4,2009-12
1,489434,79323P,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0,2009-12
2,489434,79323W,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0,2009-12
3,489434,22041,48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.8,2009-12
4,489434,21232,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0,2009-12

In [164]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 805549 entries, 0 to 1067370
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   invoice      805549 non-null  object
 1   stockcode    805549 non-null  object
 2   quantity     805549 non-null  int64
 3   invoicedate  805549 non-null  datetime64[ns]
 4   price        805549 non-null  float64
 5   customer_id  805549 non-null  int32
 6   country      805549 non-null  object
 7   total_price  805549 non-null  float64
 8   month_year   805549 non-null  period[M]
dtypes: datetime64[ns](1), float64(2), int32(1), int64(1), object(3), period[M](1)
memory usage: 58.4+ MB

In [165]:
df_clean.rename(columns={'month_year': 'invoice_month',}, inplace=True)

C:\Users\hj161\AppData\Local\Temp\ipykernel_15524\872789918.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.rename(columns={'month_year': 'invoice_month',}, inplace=True)

In [167]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 805549 entries, 0 to 1067370
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   invoice        805549 non-null  object
 1   stockcode      805549 non-null  object
 2   quantity       805549 non-null  int64
 3   invoicedate    805549 non-null  datetime64[ns]
 4   price          805549 non-null  float64
 5   customer_id    805549 non-null  int32
 6   country        805549 non-null  object
 7   total_price    805549 non-null  float64
 8   invoice_month  805549 non-null  period[M]
dtypes: datetime64[ns](1), float64(2), int32(1), int64(1), object(3), period[M](1)
memory usage: 58.4+ MB

In [169]:
df_clean.rename(columns={'invoicedate':'invoice_date'},inplace=True)
df_clean.drop(columns=['invoice_month'], inplace=True)
df_clean.to_csv('online_retail_II_full.csv', index=False)

C:\Users\hj161\AppData\Local\Temp\ipykernel_15524\1104760611.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.rename(columns={'invoicedate':'invoice_date'},inplace=True)
C:\Users\hj161\AppData\Local\Temp\ipykernel_15524\1104760611.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.drop(columns=['invoice_month'], inplace=True)

In [1]:
pip install sqlalchemy psycopg2-binary pandas

Requirement already satisfied: sqlalchemy in c:\users\hj161\anaconda3\lib\site-packages (2.0.34)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: pandas in c:\users\hj161\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hj161\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\hj161\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hj161\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hj161\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hj161\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hj161\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\hj161\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   ------------------- -------------------- 1.3/2.7 MB 1.8 MB/s eta 0:00:01
   --------------------------- ------------ 1.8/2.7 MB 2.0 MB/s eta 0:00:01
   -------------------------------------- - 2.6/2.7 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 2.3 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
Note: you may need to restart the kernel to use updated packages.